#!/usr/bin/env bash

# Use redis 2.9.7 (that supports lua scripts)
# which is running on port 6378 on cruise
export REDIS_URL=redis://localhost:6378/3

source $HOME/.rvm/scripts/rvm

# Kill the whole script on error
set -e

rvm use 1.9.3@plines --create

bundle install --without os_x

# Ensure cruise is running against the latest dependencies
bundle update

bundle exec rake cruise --trace
