#!/bin/bash

set -e -x

export SPEC_OPTS="--backtrace"

additional_rspec_opts=$1

echo "Running all..."

time bin/rspec spec --format progress --profile -rsimplecov_setup $additional_rspec_opts

echo
echo "--------------------------------------------------------------------"
echo

for file in `find spec -iname '*_spec.rb'`; do
  time bin/rspec $file --format progress
done

