#!/usr/bin/env bash

REDIS_VERSION=2.6.0-rc6

# shutdown the 2.4 server
redis-cli shutdown

# download
wget http://redis.googlecode.com/files/redis-$REDIS_VERSION.tar.gz

# extract
tar xzf redis-$REDIS_VERSION.tar.gz

# make
cd redis-$REDIS_VERSION
make

# daemonize!
echo "daemonize yes" > redis.conf

# start the 2.6 server
./src/redis-server redis.conf
